In [1]:
import numpy as np
import pandas as pd

In [2]:
bootstrap_results = pd.read_csv('../output/bootstrap_results.csv')

In [3]:
bootstrap_results.head()

,LR,RF,ADA,GB,QDA,LDA,LinearSVM,RBFSVM,Subject,feature_size
0,0.465556,0.468889,0.611111,0.375556,0.475556,0.437778,0.471111,0.425556,NF101,"(96, 12)"
1,0.374444,0.471111,0.468889,0.482222,0.448889,0.561111,0.455556,0.343333,NF101,"(96, 12)"
2,0.435556,0.551111,0.596667,0.513333,0.521111,0.504444,0.470000,0.416667,NF101,"(96, 12)"
3,0.468889,0.565556,0.476667,0.478889,0.542222,0.552222,0.480000,0.387778,NF101,"(96, 12)"
4,0.468889,0.602222,0.650000,0.417778,0.591111,0.374444,0.527778,0.393333,NF101,"(96, 12)"

In [4]:
bt_agg_subject_mean = bootstrap_results.groupby(['Subject']).mean()

In [5]:
bt_agg_subject_mean

,LR,RF,ADA,GB,QDA,LDA,LinearSVM,RBFSVM
Subject,,,,,,,,
NF101,0.485648,0.487683,0.489243,0.490653,0.498012,0.479369,0.496869,0.377447
NF103,0.486526,0.489596,0.497232,0.491524,0.493278,0.485329,0.494516,0.376673
NF104,0.490827,0.488964,0.494227,0.490342,0.498212,0.484884,0.493136,0.378147
NF105,0.485525,0.486445,0.491025,0.487715,0.478255,0.481795,0.492070,0.320170
NF106,0.488719,0.491347,0.492060,0.491003,0.497939,0.483122,0.496101,0.378181
NF107,0.492303,0.490807,0.494008,0.490831,0.494711,0.486249,0.494930,0.376984
NF108,0.491002,0.490631,0.496910,0.495327,0.495331,0.481440,0.492897,0.376314
NF109,0.489472,0.490158,0.490431,0.494093,0.496332,0.489509,0.494823,0.378132
NF110,0.487934,0.491497,0.493533,0.494468,0.499878,0.485530,0.493739,0.377897
NF111,0.481968,0.492926,0.494827,0.490948,0.498261,0.479897,0.496529,0.377814

In [6]:
bt_agg_subject_std = bootstrap_results.groupby(['Subject']).std()

In [7]:
bt_agg_subject_std

,LR,RF,ADA,GB,QDA,LDA,LinearSVM,RBFSVM
Subject,,,,,,,,
NF101,0.059103,0.060986,0.062731,0.066554,0.055848,0.065680,0.050299,0.031027
NF103,0.065305,0.059255,0.063800,0.066486,0.061555,0.067507,0.053179,0.030030
NF104,0.066505,0.059900,0.061863,0.069216,0.056163,0.065784,0.050614,0.030624
NF105,0.094036,0.086658,0.090291,0.092458,0.084976,0.091993,0.076767,0.042003
NF106,0.063572,0.058136,0.062856,0.067437,0.053642,0.065813,0.050512,0.031262
NF107,0.066861,0.059160,0.066589,0.067582,0.062663,0.067723,0.051021,0.031923
NF108,0.064894,0.059681,0.065157,0.068657,0.058361,0.065501,0.052940,0.031255
NF109,0.067855,0.060805,0.065181,0.065996,0.062029,0.067072,0.050827,0.030993
NF110,0.063197,0.058680,0.062908,0.064589,0.056108,0.064841,0.052542,0.030014
NF111,0.065990,0.058056,0.063755,0.064506,0.058364,0.066882,0.050822,0.030994

In [11]:
actual_results = pd.read_csv('../output/classify_results.csv')

In [12]:
actual_agg_subject_mean = actual_results.groupby(['Subject']).mean()

In [13]:
actual_agg_subject_mean

,LR,RF,ADA,GB,QDA,LDA,LinearSVM,RBFSVM
Subject,,,,,,,,
NF101,0.656667,0.613333,0.527778,0.685556,0.645556,0.603333,0.593333,0.336667
NF103,0.543333,0.656667,0.665556,0.730000,0.636667,0.533333,0.602222,0.336667
NF104,0.440000,0.556667,0.544444,0.501111,0.458889,0.430000,0.523333,0.336667
NF105,0.625000,0.750000,0.705000,0.830000,0.610000,0.560000,0.645000,0.335000
NF106,0.696667,0.761111,0.721111,0.710000,0.731111,0.646667,0.584444,0.336667
NF107,0.395556,0.555556,0.563333,0.511111,0.593333,0.448889,0.461111,0.336667
NF108,0.574444,0.530000,0.543333,0.450000,0.565556,0.574444,0.522222,0.336667
NF109,0.532222,0.634444,0.672222,0.624444,0.636667,0.551111,0.430000,0.336667
NF110,0.633333,0.538889,0.621111,0.610000,0.557778,0.603333,0.574444,0.336667
NF111,0.513333,0.604444,0.606667,0.511111,0.532222,0.606667,0.431111,0.336667